# NOTE(Jack): Currently there are no other sub options except for circle grid! For april grid3 the tag family is at
# this time hardcoded but in future we could add another section like april_grid3_options. It should be clear to the
# that these options are only read when the target.type matches the options.

target:
  type: "april_grid3" # checkerboard, circle_grid, april_grid3
  pattern_size: [ 3,4 ] # [row, column]
  unit_dimension: 0.05 # (m)
  # Only loaded and used if type == circle_grid, left here for posterity
  circle_grid_options:
    asymmetric: false
